apps/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.RaffleListView.as_view(), name="index"),
    path("check_reference", views.comprobar, name="check_reference"),
    path(
        "raffle/<int:pk>/participant/compete/",
        views.ParticipantCreateView.as_view(),
        name="raffle",
    ),
]

apps/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = "users"
urlpatterns = [
    path(
        "profile/update/", views.CurrentUserUpdateView.as_view(), name="profile_update"
    ),
    path("users/", views.UserListView.as_view(), name="list"),
    path("users/<int:pk>/details/", views.UserDetailView.as_view(), name="detail"),
    path("user/create/", views.UserCreateView.as_view(), name="create"),
    path("user/<int:pk>/edit/", views.UserUpdateView.as_view(), name="edit"),
    path(
        "user/<int:pk>/delete/", views.UserDeleteView.as_view(), name="delete"
    ),  # Eliminar usuario
    path("login/", views.login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

config/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("home.urls", namespace="home")),
    path("", include("users.urls", namespace="users")),
    path("", include("raffles.urls", namespace="raffles")),
    path("tinymce/", include("tinymce.urls")),
]

# Añadir configuración para servir archivos de medios en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]

apps/users/models.py
# models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
import os
from datetime import datetime
import re
from io import BytesIO
from PIL import Image
from django.core.files.base import ContentFile


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("El email debe ser proporcionado")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("El superusuario debe tener is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("El superusuario debe tener is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


def sanitize_filename(filename):
    # Eliminar caracteres no alfanuméricos (excepto puntos, guiones y guiones bajos)
    return re.sub(r"[^\w\-_\.]", "", filename)


class ImageManagementMixin:
    def save(self, *args, **kwargs):
        """
        Guarda la instancia y maneja la optimización y eliminación de imágenes.
        """
        # Verifica si la instancia es nueva o está siendo editada
        is_new_instance = not self.pk

        for field_name, settings in self.image_fields.items():
            image_field = getattr(self, field_name, None)

            if is_new_instance and image_field:
                # Nueva instancia con imagen, optimiza la imagen
                # print(f"Procesando nueva imagen para {field_name}")
                self._optimize_image(
                    image_field, settings["dimensions"], settings["quality"]
                )

            elif not is_new_instance:
                # Instancia existente, verifica si la imagen ha cambiado
                if self._image_changed(field_name):
                    # print(f"Imagen {field_name} ha cambiado: True")

                    old_instance = self.__class__.objects.get(pk=self.pk)
                    old_image = getattr(old_instance, field_name, None)

                    if old_image:
                        # print(f"Eliminando imagen previa para {field_name}")
                        self._delete_image(old_image)

                    if image_field:
                        # Optimiza la nueva imagen
                        # print(f"Optimizando nueva imagen para {field_name}")
                        self._optimize_image(
                            image_field, settings["dimensions"], settings["quality"]
                        )
                # else:
                #     # Imagen no ha cambiado
                #     print(
                #         f"Imagen {field_name} no ha cambiado, no se realiza ninguna acción."
                #     )

            elif image_field is None and not is_new_instance:
                # Campo vacío en una instancia existente
                old_instance = self.__class__.objects.get(pk=self.pk)
                old_image = getattr(old_instance, field_name, None)

                if old_image:
                    # print(
                    #     f"Eliminando imagen previa para {field_name} porque el campo está vacío"
                    # )
                    self._delete_image(old_image)

        # No llamamos a super().save() aquí

    def delete(self, *args, **kwargs):
        """
        Elimina las imágenes asociadas antes de eliminar la instancia.
        """
        for field_name in self.image_fields:
            image_field = getattr(self, field_name, None)
            if image_field:
                # print(f"Eliminando imagen para el campo {field_name}")
                self._delete_image(image_field)

    def _image_changed(self, field_name):
        """
        Comprueba si la imagen ha cambiado en una instancia existente.
        """
        if not self.pk:
            return False  # Si el objeto no está guardado, no se ha cambiado la imagen
        old_instance = self.__class__.objects.get(pk=self.pk)
        old_image = getattr(old_instance, field_name)
        new_image = getattr(self, field_name)
        return old_image != new_image

    def _optimize_image(self, image, dimensions, quality):
        """
        Función para optimizar la imagen.
        """
        img = Image.open(image)
        img.thumbnail(dimensions, Image.LANCZOS)

        if img.mode != "RGB":
            img = img.convert("RGB")

        output = BytesIO()
        img.save(output, format="JPEG", quality=quality, optimize=True)
        output.seek(0)

        image.save(image.name, ContentFile(output.getvalue()), save=False)

    def _delete_image(self, image):
        """
        Elimina la imagen si existe en el sistema de archivos.
        """
        if image and os.path.isfile(image.path):
            # print(f"Eliminando archivo de imagen: {image.path}")
            os.remove(image.path)


def user_profile_picture_path(instance, filename):
    # Obtener la extensión del archivo original
    ext = os.path.splitext(filename)[1]

    # Sanitizar el correo electrónico para usarlo como parte del nombre del archivo
    safe_email = sanitize_filename(instance.email.split("@")[0])

    # Generar el nuevo nombre de archivo
    timestamp = datetime.now().strftime("%m-%d-%Y_%H-%M-%S")
    filename = f"{safe_email}_{timestamp}{ext}"

    # Retornar la ruta completa
    return os.path.join("profile_pictures", filename)


class UserAccount(AbstractUser, ImageManagementMixin):
    username = None  # Eliminamos el campo de username
    email = models.EmailField(
        unique=True, verbose_name="correo electrónico"
    )  # Hacemos que el email sea único
    profile_picture = models.ImageField(
        upload_to=user_profile_picture_path,
        blank=True,
        null=True,
        verbose_name="imagen de perfil",
    )

    groups = models.ManyToManyField(
        "auth.Group",
        related_name="user_set",  # Evitar colisión con auth.User.groups
        blank=True,
        help_text="Los grupos a los que pertenece este usuario.",
        verbose_name="grupos",
    )

    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="user_set",  # Evitar colisión con auth.User.user_permissions
        blank=True,
        help_text="Permisos específicos para este usuario.",
        verbose_name="permisos de usuario",
    )

    USERNAME_FIELD = "email"  # Indicamos que el campo de identificación es el email
    REQUIRED_FIELDS = []  # No se requiere ningún otro campo

    objects = UserManager()

    # Configuración para los campos de imagen
    image_fields = {
        "profile_picture": {
            "max_size": 5,  # Tamaño máximo en MB
            "dimensions": (300, 300),  # Dimensiones de optimización
            "quality": 100,  # Calidad de compresión JPEG
        }
    }

    class Meta:
        db_table = "user_account"  # Nombre con el que se guarda en la base de datos
        verbose_name = "usuario"  # Nombre en singular
        verbose_name_plural = "usuarios"  # Nombre en plural
        permissions = [
            (
                "change_permissions_user",
                "Puede gestionar permisos de usuario",
            ),
        ]
    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        # Procesar imágenes usando el mixin
        ImageManagementMixin.save(self, *args, **kwargs)
        # Llamar al save del modelo de Django
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Procesar eliminación de imágenes usando el mixin
        ImageManagementMixin.delete(self, *args, **kwargs)
        # Llamar al delete del modelo de Django
        super().delete(*args, **kwargs)

theme/templates/includes/footer.html
{% load static %}
<footer class="bg-white dark:bg-gray-900">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
            <div class="flex mb-6 md:mb-0 items-center justify-center">
                <a href="{% url 'home:index' %}" class="flex items-center">
                    <img src="{% get_media_prefix %}img/logo.png" class="h-32 me-3" alt="Logo" />
                </a>
            </div>
            <div class="flex flex-col items-center justify-center">
                <!-- Texto de Redes Sociales -->
                <p class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                    ¡Síguenos en nuestras
                    redes sociales!
                </p>
                <!-- Redes Sociales -->
                <div class="grid grid-cols-5 gap-6 ">
                    <a href="#"
                       class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                        <svg class="w-8 h-8"
                             fill="currentColor"
                             viewBox="0 0 24 24"
                             aria-hidden="true">
                            <!-- Icono de Whatsapp -->
                            <path fill="currentColor" fill-rule="evenodd" d="M12 4a8 8 0 0 0-6.895 12.06l.569.718-.697 2.359 2.32-.648.379.243A8 8 0 1 0 12 4ZM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10a9.96 9.96 0 0 1-5.016-1.347l-4.948 1.382 1.426-4.829-.006-.007-.033-.055A9.958 9.958 0 0 1 2 12Z" clip-rule="evenodd" />
                            <path fill="currentColor" d="M16.735 13.492c-.038-.018-1.497-.736-1.756-.83a1.008 1.008 0 0 0-.34-.075c-.196 0-.362.098-.49.291-.146.217-.587.732-.723.886-.018.02-.042.045-.057.045-.013 0-.239-.093-.307-.123-1.564-.68-2.751-2.313-2.914-2.589-.023-.04-.024-.057-.024-.057.005-.021.058-.074.085-.101.08-.079.166-.182.249-.283l.117-.14c.121-.14.175-.25.237-.375l.033-.066a.68.68 0 0 0-.02-.64c-.034-.069-.65-1.555-.715-1.711-.158-.377-.366-.552-.655-.552-.027 0 0 0-.112.005-.137.005-.883.104-1.213.311-.35.22-.94.924-.94 2.16 0 1.112.705 2.162 1.008 2.561l.041.06c1.161 1.695 2.608 2.951 4.074 3.537 1.412.564 2.081.63 2.461.63.16 0 .288-.013.4-.024l.072-.007c.488-.043 1.56-.599 1.804-1.276.192-.534.243-1.117.115-1.329-.088-.144-.239-.216-.43-.308Z" />
                        </svg>
                    </a>
                    <a href="#"
                       class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                        <svg class="w-8 h-8"
                             fill="currentColor"
                             viewBox="0 0 24 24"
                             aria-hidden="true">
                            <!-- Icono de Facebook -->
                            <path fill-rule="evenodd" d="M13.135 6H15V3h-1.865a4.147 4.147 0 0 0-4.142 4.142V9H7v3h2v9.938h3V12h2.021l.592-3H12V6.591A.6.6 0 0 1 12.592 6h.543Z" clip-rule="evenodd" />
                        </svg>
                    </a>
                    <a href="#"
                       class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                        <svg class="w-8 h-8"
                             fill="currentColor"
                             viewBox="0 0 24 24"
                             aria-hidden="true">
                            <!-- Icono de X -->
                            <path d="M13.795 10.533 20.68 2h-3.073l-5.255 6.517L7.69 2H1l7.806 10.91L1.47 22h3.074l5.705-7.07L15.31 22H22l-8.205-11.467Zm-2.38 2.95L9.97 11.464 4.36 3.627h2.31l4.528 6.317 1.443 2.02 6.018 8.409h-2.31l-4.934-6.89Z" />
                        </svg>
                    </a>
                    <a href="#"
                       class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                        <svg class="w-8 h-8"
                             fill="currentColor"
                             viewBox="0 0 24 24"
                             aria-hidden="true">
                            <!-- Icono de Instagram -->
                            <path fill="currentColor" fill-rule="evenodd" d="M3 8a5 5 0 0 1 5-5h8a5 5 0 0 1 5 5v8a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5V8Zm5-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V8a3 3 0 0 0-3-3H8Zm7.597 2.214a1 1 0 0 1 1-1h.01a1 1 0 1 1 0 2h-.01a1 1 0 0 1-1-1ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm-5 3a5 5 0 1 1 10 0 5 5 0 0 1-10 0Z" clip-rule="evenodd" />
                        </svg>
                    </a>
                    <a href="#"
                       class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                        <svg class="w-8 h-8"
                             fill="currentColor"
                             viewBox="0 0 24 24"
                             aria-hidden="true">
                            <!-- Icono de Youtube -->
                            <path fill-rule="evenodd" d="M21.7 8.037a4.26 4.26 0 0 0-.789-1.964 2.84 2.84 0 0 0-1.984-.839c-2.767-.2-6.926-.2-6.926-.2s-4.157 0-6.928.2a2.836 2.836 0 0 0-1.983.839 4.225 4.225 0 0 0-.79 1.965 30.146 30.146 0 0 0-.2 3.206v1.5a30.12 30.12 0 0 0 .2 3.206c.094.712.364 1.39.784 1.972.604.536 1.38.837 2.187.848 1.583.151 6.731.2 6.731.2s4.161 0 6.928-.2a2.844 2.844 0 0 0 1.985-.84 4.27 4.27 0 0 0 .787-1.965 30.12 30.12 0 0 0 .2-3.206v-1.516a30.672 30.672 0 0 0-.202-3.206Zm-11.692 6.554v-5.62l5.4 2.819-5.4 2.801Z" clip-rule="evenodd" />
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
        <div class="sm:flex justify-center">
            <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 <a href="" class="hover:underline">AGROFINCA LA PEÑERA RANCH R.A, C.A</a>.
                Todos los derechos reservados.
            </span>
        </div>
    </div>
</footer>

theme/templates/includes/header.html
{% load static %}
<nav class="bg-white border-gray-200 dark:bg-gray-900 mb-4">
    <div class="max-w-screen-xl flex flex-wrap items-center  justify-center gap-4 xs:justify-between mx-auto p-4">
        <a href="{% url 'home:index' %}"
           class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% get_media_prefix %}img/logo.png"
                 class="h-16 sm:h-24"
                 alt="Logo" />
        </a>
        <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            {% include "./login.html" %}
            <button data-collapse-toggle="navbar-user"
                    type="button"
                    class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                    aria-controls="navbar-user"
                    aria-expanded="false">
                <span class="sr-only">Abrir menú</span>
                <svg class="w-5 h-5"
                     aria-hidden="true"
                     xmlns="http://www.w3.org/2000/svg"
                     fill="none"
                     viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15" />
                </svg>
            </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
             id="navbar-user">
            <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <a href="{% url 'home:index' %}"
                       class="block py-2 px-3 text-white bg-pink-700 rounded md:bg-transparent md:text-pink-700 md:p-0 md:dark:text-pink-500"
                       aria-current="page">Inicio</a>
                </li>
                <li>
                    <a href="{% url 'home:check_reference' %}"
                       class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-pink-700 md:p-0 dark:text-white md:dark:hover:text-pink-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Comprobar pago</a>
                </li>
                <li>
                    <a href="#"
                       class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-pink-700 md:p-0 dark:text-white md:dark:hover:text-pink-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contáctanos</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

theme/templates/includes/login.html
{% if user.is_authenticated %}
    <button type="button"
            class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
            id="user-menu-button"
            aria-expanded="false"
            data-dropdown-toggle="user-dropdown"
            data-dropdown-placement="bottom">
        <span class="sr-only">Abrir menú de usuario</span>
        {% if user.profile_picture %}
            <img src="{{ user.profile_picture.url }}"
                 class="rounded-full size-10"
                 alt="">
        {% else %}
            <svg class="rounded-full size-10 text-white"
                 aria-hidden="true"
                 xmlns="http://www.w3.org/2000/svg"
                 fill="currentColor"
                 viewBox="0 0 24 24">
                <path fill-rule="evenodd" d="M12 20a7.966 7.966 0 0 1-5.002-1.756l.002.001v-.683c0-1.794 1.492-3.25 3.333-3.25h3.334c1.84 0 3.333 1.456 3.333 3.25v.683A7.966 7.966 0 0 1 12 20ZM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10c0 5.5-4.44 9.963-9.932 10h-.138C6.438 21.962 2 17.5 2 12Zm10-5c-1.84 0-3.333 1.455-3.333 3.25S10.159 13.5 12 13.5c1.84 0 3.333-1.455 3.333-3.25S13.841 7 12 7Z" clip-rule="evenodd" />
            </svg>
        {% endif %}
    </button>
    <!-- Dropdown menu -->
    <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600"
         id="user-dropdown">
        <div class="px-4 py-3">
            <span class="block text-sm">
                {% if user.first_name and user.last_name %}
                    {{ user.first_name }} {{ user.last_name }}
                {% else %}
                    Nombre no disponible
                {% endif %}
            </span>
            <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">
                {% if user.email %}
                    {{ user.email }}
                {% else %}
                    Correo no disponible
                {% endif %}
            </span>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
            {% if perms.users.view_useraccount or perms.users.add_useraccount %}
                <li>
                    <a href="{% url 'users:list' %}"
                       class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Gestión de usuarios</a>
                </li>
            {% endif %}
            {% if perms.raffles.view_raffle or perms.raffles.add_raffle %}
                <li>
                    <a href="{% url "raffles:list" %}"
                       class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Gestión de rifas</a>
                </li>
            {% endif %}
            <li>
                <a href="{% url "users:profile_update" %}"
                   class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Mi cuenta</a>
            </li>
            <li>
                <!-- En el template HTML -->
                <form action="{% url 'users:logout' %}"
                      method="post"
                      class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">
                    {% csrf_token %}
                    <button href="#" type="submit">
                        Cerrar
                        sesión
                    </button>
                </form>
            </li>
        </ul>
    </div>
{% else %}
    <!-- Modal toggle -->
    <button data-modal-target="authentication-modal"
            data-modal-toggle="authentication-modal"
            class="text-white bg-gradient-to-br from-pink-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
            type="button">Iniciar sesión</button>
    <!-- Main modal -->
    {% include "./modal_login.html" %}
{% endif %}

theme/templates/includes/modal_login.html
<div id="authentication-modal"
     tabindex="-1"
     aria-hidden="true"
     class="hidden overflow-y-auto overflow-x-hidden fixed top-0 left-0 right-0 z-50 flex justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-sm max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">Accede a nuestra plataforma</h3>
                <button type="button"
                        class="end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-hide="authentication-modal">
                    <svg class="w-3 h-3"
                         aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Cerrar</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5">
                <form class="space-y-4" action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    <div>
                        <label for="email"
                               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                            Tu
                            correo electrónico
                        </label>
                        <input type="email"
                               name="email"
                               id="email"
                               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                               placeholder="name@company.com"
                               required />
                    </div>
                    <div>
                        <label for="password"
                               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                            Tu contraseña
                        </label>
                        <input type="password"
                               name="password"
                               id="password"
                               placeholder="••••••••"
                               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                               required />
                    </div>
                    <div class="flex justify-between">
                        <div class="flex items-start">
                            <div class="flex items-center h-5">
                                <input id="remember_me"
                                       type="checkbox"
                                       name="remember_me"
                                       value=""
                                       class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-pink-300 dark:bg-gray-600 dark:border-gray-500 dark:focus:ring-pink-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800" />
                            </div>
                            <label for="remember"
                                   class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Recuérdame</label>
                        </div>
                        <a href="#"
                           class="text-sm text-pink-700 hover:underline dark:text-pink-500">¿Perdiste tu
                        contraseña?</a>
                    </div>
                    <div>
                        <button type="submit"
                                class="w-full text-white bg-gradient-to-br from-pink-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">
                            Iniciar sesión
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>